import logging
import subprocess
import time
import yaml
import libnmstate
import configparser
from enum import Enum
from typing import Optional, List, Dict, Any, Tuple
from pathlib import Path

# set libnmstate log level
logging.getLogger('libnmstate').setLevel(logging.ERROR)

class ArtifactManager:
    """load config file and set artifacts directory."""
    
    def __init__(self) -> None:
        self.base_dir: Path = Path.home() / ".local/bcocinero"
        self.jefe_file: Path = self.base_dir / "JEFE"
        self.artifact_dir = self.get_artifact_dir()
        self.install_root_file: Path = self.artifact_dir / "INSTALL_ROOT"

    def get_artifact_dir(self) -> Path:
        """return artifacts_dir path."""
        artifact_dir = self.base_dir / "artifacts"
        artifact_dir.mkdir(parents=True, exist_ok=True)

        return artifact_dir

    def save_state(self, filename: str, state: Dict[str, Any]) -> Path:
        """save network state to yaml file."""
        target: Path = self.artifact_dir / filename
        with open(target, "w", encoding="utf-8") as f:
            yaml.dump(state, f, default_flow_style=False, allow_unicode=True)

        return target

    def save_install_root_file(self, install_root_dir: str) -> Tuple[bool, str]:
        try:
            with open(self.install_root_file, "w", encoding="utf-8") as f:
                f.write(install_root_dir)
            return (True, f"Succeed to save INSTALL_ROOT_FILE")
        except OSError as e:
            return (False, f"Fail to save INSTALL_ROOT_FILE: {e.strerror}")

    def get_install_root(self) -> Optional[str]:
        try:
            with open(self.install_root_file, "r", encoding="utf-8") as f:
                return f.read().strip()
        except Exception:
            return None

class ProfileType(Enum):
    SERVICE = "service"
    MANAGEMENT = "management"
    STORAGE = "storage"
    PROVIDER = "provider"
    NONE = ""

    @classmethod
    def list_values(cls, type: str = "all") -> List[str]:
        l_values = [item.value for item in cls if item != cls.NONE]
        if type == "vlan":
            l_values.remove("provider")

        return l_values

class NodeRole(Enum):
    HEAD = "HeadControl"
    CONTROL = "Control"
    COMPUTE = "Compute"
    STORAGE = "Storage"
    NONE = ""

    @property
    def is_control_type(self) -> bool:
        return self in (NodeRole.HEAD, NodeRole.CONTROL)

    @classmethod
    def has_value(cls, value: str) -> bool:
      return value in [ item.value for item in cls]

    @classmethod
    def from_str(cls, value: str):
        for item in cls:
            if item.value == value:
                return item
        return cls.NONE

class InventoryGenerator:
    def __init__(self, hosts_data: List[Dict[str, Any]]):
        self.hosts = []
        for h in hosts_data:
            self.hosts.append({
                "hostname": h["hostname"],
                "mgmt_ip": h["mgmt_ip"],
                "role": NodeRole.from_str(h["role"])
            })

    def generate(self, output_file: str = "hosts"):
        lines = []

        lines.append("### generated by bcocinero ###")
        for h in self.hosts:
            host_line = f"{h['hostname']} ip={h['mgmt_ip']}"
            if h['role'] == NodeRole.HEAD:
                host_line += " ansible_connection=local ansible_python_interpreter=/usr/bin/python3"
            lines.append(host_line)

        storage_nodes = [h['hostname'] for h in self.hosts if h['role'] ==
                NodeRole.STORAGE]
        num_storage = len(storage_nodes)
        if num_storage >= 3:
            ceph_config = {
                "[mons]": storage_nodes[:3],
                "[mgrs]": storage_nodes[:2],
                "[osds]": storage_nodes,
                "[rgws]": storage_nodes[-2:]
            }
        elif num_storage > 0:
            ceph_config = {
                "[mons]": [storage_nodes[0]],
                "[mgrs]": [storage_nodes[0]],
                "[osds]": storage_nodes,
                "[rgws]": [storage_nodes[-1]]
            }
        else:
            ceph_config = {
                "[mons]": [], "[mgrs]": [], "[osds]": [], "[rgws]": []
            }
        lines.append("\n# ceph nodes")
        for group, members in ceph_config.items():
            lines.append(group)
            lines.extend(members)
            lines.append("")

        control_nodes = [h['hostname'] for h in self.hosts if h['role'].is_control_type]
        compute_nodes = [h['hostname'] for h in self.hosts if h['role']  == NodeRole.COMPUTE]
        lines.append("[clients]")
        lines.extend(control_nodes + compute_nodes)

        lines.append("\n# kubernetes nodes")
        lines.append("[kube_control_plane]")
        lines.extend(control_nodes)
        lines.append("\n[kube_node]")
        lines.extend(control_nodes + compute_nodes)
        
        lines.append("\n# openstack nodes")
        lines.append("[controller-node]")
        lines.extend(control_nodes)
        lines.append("\n[compute-node]")
        lines.extend(compute_nodes)

        lines.append("\n[etcd]")
        if len(control_nodes) >= 3:
            lines.extend(control_nodes)
        else:
            etcd_nodes = list(control_nodes)
            if compute_nodes:
                etcd_nodes.append(compute_nodes[0])
            lines.extend(etcd_nodes)
        lines.append("")

        expert_section = """
###################################################
## Do not touch below if you are not an expert!!! #
###################################################
[ceph_servers:children]
mons
mgrs
osds
rgws

[ceph:children]
ceph_servers
clients

[k8s_cluster:children]
kube_control_plane
kube_node

[network-node:children]
controller-node

[controller-node:vars]
node_labels={"openstack-control-plane":"enabled"}

[network-node:vars]
node_labels={"openstack-network-plane":"enabled"}

[compute-node:vars]
node_labels={"openstack-compute-node":"enabled", "openvswitch":"enabled"}
# powerflex nodes
[mdm]
[sds]
[sdc]
[pfmp]
[pfmp_installer]
[pfmp_mvm]
[pfmp_node]
[powerflex:children]
mdm
sds
sdc

# kubespray host groups
[calico_rr]
[bastion]
"""
        lines.append(expert_section)

        try:    
            with open(output_file, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
            logging.debug(f"Host inventory is created: {output_file}")
        except Exception as e:
            logging.error(f"Fail to create the host inventory: {e}")

class NetworkManager:
    """Class for reading and setting of network interfaces"""
    _STATE_TTL = 3.0

    def __init__(self) -> None:
        self.am = ArtifactManager()
        self._cached_state: Optional[Dict[str, Any]] = None
        self._cache_time: float = 0.0

    def show_state(self, force: bool = False) -> Dict[str, Any]:
        """Return the current network state."""
        now = time.monotonic()
        cache_expired = (now - self._cache_time) > self._STATE_TTL
        if force or self._cached_state is None or cache_expired:
            self._cached_state = libnmstate.show()
            self._cache_time = now
        return self._cached_state

    def apply_state(self, state: Dict[str, Any]) -> None:
        """apply the configured network state."""
        try:
            libnmstate.apply(state)
            self._cached_state = None
        except Exception as e:
            raise RuntimeError(f"Fail to apply the state: {e}")

    # Read operations
    def get_machine_id(self) -> Optional[str]:
        try:
            with open("/etc/machine-id", "r") as f:
                return f.read().strip()
        except FileNotFoundError:
            return None

    def get_interface_by_profile(self, profile_name: str) -> Optional[str]:
        """get interface by profile-name"""
        try:
            state = self.show_state()
            interfaces = state.get("interfaces", [])

            for iface in interfaces:
                if iface.get("profile-name", "") == profile_name:
                    return iface
            return None
        except Exception as e:
            return None

    def get_mgmt_iface_info(self) -> Tuple[Optional[str], Optional[str]]:
        my_mgmt_ip = None
        my_mgmt_name = None
        iface = self.get_interface_by_profile(ProfileType.MANAGEMENT.value)

        if iface:
            my_mgmt_name = iface.get("name")
            ipv4_info = iface.get("ipv4", {})
            addresses = ipv4_info.get("address", [])

            if addresses:
                my_mgmt_ip = addresses[0].get("ip")

        return my_mgmt_ip, my_mgmt_name

    def get_host_info(self) -> Dict[str, Any]:
        """get hostname and nameservers."""
        state = self.show_state()
        dns_resolver = state.get("dns-resolver", {}).get("running", {})
        role = ""
        hc_ip = None
        mgmt_ip, mgmt_name = self.get_mgmt_iface_info()
        machine_id = self.get_machine_id()

        try:
            result = subprocess.run(
                ["sudo", "hostnamectl", "deployment"],
                capture_output=True,
                text=True,
                check=True
            )
            if NodeRole.has_value(result.stdout.strip()):
                role = result.stdout.strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            pass

        if self.am.jefe_file.exists():
            try:
                content = self.am.jefe_file.read_text(encoding="utf-8").strip()
                if content:
                    hc_ip = content
            except OSError:
                pass

        return {
            "machine_id": machine_id,
            "hostname": state.get("hostname", {}).get("running", ""),
            "nameservers": dns_resolver.get("server", []),
            "role": role,
            "hc_ip": hc_ip,
            "mgmt_ip": mgmt_ip,
            "mgmt_name": mgmt_name
        }

    def get_default_gateway(self) -> Optional[Dict[str, str]]:
        state = self.show_state()
        routes = state.get("routes", {}).get("running", [])
        for route in routes:
            if route.get("destination") == "0.0.0.0/0":
                return {
                    "gateway": route.get("next-hop-address"),
                    "interface": route.get("next-hop-interface")
                }
        return None

    def get_interface_info(self, name: str) -> Dict[str, Any]:
        """return the interface info."""
        state = self.show_state()
        return next(
            (iface for iface in state.get("interfaces", [])
                if iface.get("name") == name), {}
        )

    def list_interfaces(self,
            iface_types: Optional[List[str]] = None) -> List[Dict[str, Any]]:
        state = self.show_state()
        allowed = iface_types or ["ethernet", "bond", "vlan"]
        return [
            iface for iface in state.get("interfaces", [])
            if iface.get("type") in allowed
        ]

    def get_vlan_interfaces(self) -> List[Tuple[str, str, str, str, str]]:
        l_vlan: List[Tuple[str, str, str, str, str]] = []
        for iface in self.list_interfaces(["vlan"]):
            vconfig = iface.get("vlan", {})
            ipv4_list = iface.get("ipv4", {}).get("address", [])
            ip = ipv4_list[0].get("ip", "") if ipv4_list else ""
            prefix = ipv4_list[0].get("prefix-length", "") if ipv4_list else ""
            ip_str = f"{ip}/{prefix}"
            
            l_vlan.append((
                iface.get("name", ""),
                iface.get("profile-name", ""),
                vconfig.get("base-iface", ""),
                str(vconfig.get("id", "")),
                ip_str,
                iface.get("state", "")
            ))
        return l_vlan

    def get_bond_interfaces(self) -> List[Tuple[str, str, str, str]]:
        l_bond: List[Tuple[str, str, str, str]] = []
        for iface in self.list_interfaces(["bond"]):
            bconfig = iface.get("link-aggregation", {})
            l_bond.append((
                iface.get("name", ""),
                iface.get("profile-name", "-"),
                "/".join(bconfig.get("port", [])),
                bconfig.get("mode", ""),
                iface.get("state", "")
            ))
        return l_bond

    # execute operations
    def set_hostname(self, hostname: str) -> Dict[str, Any]:
        """return hostname desired state."""
        return {
            "hostname": {
                "config": hostname
            }
        }

    def set_role(self, role: str) -> Tuple[bool, str]:
        """set host role using hostnamectl deployment."""
        try:
            result = subprocess.run(
                ["sudo", "hostnamectl", "deployment", role],
                check=True,
                capture_output=True,
                text=True
            )
            if role == NodeRole.HEAD.value:
                from bjefe.main import BjefeDaemon
                bjd = BjefeDaemon()
                bjd.setup_systemd_service()
            else:
                from bcocinerod.main import BcocineroDaemon
                bcd = BcocineroDaemon()
                bcd.setup_systemd_service()
            return (True, f"Succeed to set the role: {role}")
        except subprocess.CalledProcessError as e:
            return (False, str(e))
        except FileNotFoundError:
            return (False, "hostnamectl command not found.")

    def set_head_control_ip(self, hc_ip: str) -> Tuple[bool, str]:
        try:
            with open(self.am.jefe_file, "w", encoding="utf-8") as f:
                f.write(hc_ip)
            return (True, f"Succeed to save the Head Control IP.")
        except OSError as e:
            return (False, f"Fail to save the Head Control IP: {e.strerror}")

    def set_dns_servers(self, servers: List[str]) -> Dict[str, Any]:
        """return nameservers desired state."""
        return {
            "dns-resolver": {
                "config": {"server": servers}
            }
        }

    def create_bond_state(self,
                          name: str,
                          ports: List[str],
                          mode: str = "active-backup",
                          is_provider: bool = False) -> Dict[str, Any]:
        interfaces = [{"name": port, "state": "up"} for port in ports]
        bond_interface = {
            "name": name,
            "type": "bond",
            "state": "up",
            "link-aggregation": {
                "mode": mode,
                "port": ports,
                "options": {"miimon": "100"}
            }
        }
        bond_interface["profile-name"] = name
        if is_provider:
            bond_interface["profile-name"] = "provider"

        interfaces.append(bond_interface)

        return {"interfaces": interfaces}

    def create_vlan_state(self, name: str, base_iface: str, vlan_id: int, 
                          ip: str = "", prefix: int = 24,
                          gw: str = "", profile: str = "") -> Dict[str, Any]:
        vlan_iface: Dict[str, Any] = {
            "name": name, "type": "vlan", "state": "up",
            "vlan": {"base-iface": base_iface, "id": vlan_id}
        }
        if profile:
            vlan_iface["profile-name"] = profile
        if ip:
            vlan_iface["ipv4"] = {
                "enabled": True,
                "address": [{"ip": ip.strip(), "prefix-length": prefix}],
                "dhcp": False
            }

        desired_state = {"interfaces": [vlan_iface]}
        if ip and gw:
            desired_state["routes"] = {
                "config": [{
                    "destination": "0.0.0.0/0",
                    "next-hop-address": gw.strip(),
                    "next-hop-interface": name
                }]
            }
        return desired_state

    def delete_interface_state(self, name: str) -> Dict[str, Any]:
        return {"interfaces": [{"name": name, "state": "absent"}]}

